name: Jest coverage badge
on: 
  push:
    branches:
      - master
jobs:
  badge:
    steps:
    - uses: ./.github/workflows/build-ubuntu.yaml
    - uses: ./.github/workflows/checkout.yaml
    - uses: ./.github/workflows/install.yaml
    - name: Run tests
      run: yarn test:ci
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: master