name: Jest coverage badge
on: 
  push:
    branches:
      - master
jobs:
  badge:
    if: "!contains(github.event.head_commit.message, 'chore: release')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test:ci
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: master