# This workflow will install dependencies, create coverage tests and run Jest Coverage Comment
# For more information see: https://github.com/MishaKav/jest-coverage-comment/
name: Jest coverage comment
on:
  pull_request:
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for release
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Release'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: |
        npx jest --coverage --coverageReporters json-summary
    - name: Jest coverage comment
      uses: MishaKav/jest-coverage-comment@main
