name: Jest coverage badge
on: 
  push:
    branches:
      - master
jobs:
  build:
    steps:
    - uses: ./.github/workflows/build-ubuntu
    - uses: ./.github/workflows/checkout
    - uses: ./.github/workflows/install
    - name: Run tests
      run: yarn test:ci
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: master