name: Jest coverage badge
on: 
  push:
    branches:
      - master
jobs:
  badge:
    if: "!contains(github.event.head_commit.message, 'chore: release')"
    runs-on: ubuntu-latest
    steps:
    - name: Wait for release
      uses: lewagon/wait-on-check-action@v1.2.0
      with:
        ref: ${{ github.ref }}
        check-name: 'Release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test:ci
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: master