# This workflow will install dependencies, create coverage tests and run Jest Coverage Comment
# For more information see: https://github.com/MishaKav/jest-coverage-comment/
name: Jest coverage comment
on:
  pull_request:
jobs:
  build:
    - uses: ./.github/workflows/build-ubuntu
    - uses: ./.github/workflows/checkout
    - uses: ./.github/workflows/install
    - name: Run tests
      run: |
        npx jest --coverage --coverageReporters json-summary
    - name: Jest coverage comment
      uses: MishaKav/jest-coverage-comment@main
