name: Purge jsDelivr Cache
on:
  push:
    branches:
      - master
jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-20.04
    steps:
      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/map3xyz/payments-sdk@latest/dist/global/index.js
            https://cdn.jsdelivr.net/gh/map3xyz/payments-sdk@latest/dist/global/index.css