# This workflow will install dependencies, run build, run semantic-release and push dist using https://github.com/actions-js/push
name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Create local changes
      run: |
        yarn install
        GH_TOKEN=${{ secrets.RELEASE_TOKEN }} yarn release
    - name: Pushing to the protected branch 'master'
        - uses: CasperWA/push-protected@v2
          with:
            token: ${{ secrets.RELEASE_TOKEN }}
            branch: master

