# This workflow will install dependencies and run tests on pull requests
name: Jest Test Suite
on:
  pull_request:
jobs:
  test:
    uses: ./.github/workflows/build-ubuntu
    steps:
      - uses: ./.github/workflows/checkout
      - uses: ./.github/workflows/install
      - name: Run tests
        run: yarn test:ci
